[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-conversions"
version = "0.1.0"
description = "Tiny package with weight and distance conversions."
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Marcel", email = "marcel@seneca.ca" }]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://example.com/simple-conversions"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]
include = ["*"]
exclude = ["simpleconversions.tests*"]  # empty by default

